name: SSH Deploy

on:
    push:
        branches:
            - master # Cấu hình workflow được kích hoạt khi push code lên branch master

jobs:
    deploy:
        runs-on: ubuntu-latest # Chọn một runner phù hợp với công việc của bạn

        steps:
            - name: Checkout code
              uses: actions/checkout@v4 # Sử dụng action để checkout code từ repository

            - name: Setup node
              uses: actions/setup-node@v4 # Sử dụng action để setup nodejs
              with: # Cấu hình phiên bản nodejs
                  node-version: "20"

            - name: Install PM2
              run: npm install pm2 -g # Cài đặt PM2 global

            - name: Install dependencies
              run: npm install # Cài đặt các dependencies
              working-directory: ./server

            - name: Install SSH client
              run: sudo apt-get install openssh-client -y # Cài đặt SSH client trên runner

            - name: Setup SSH key

              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
                  chmod 644 ~/.ssh/known_hosts

            - name: Deploy code
              run: |
                  ssh -i ~/.ssh/id_rsa ${{ secrets.USER }}@${{ secrets.HOST }} "cd /var/www/node-test/server && git pull origin master" && pm2 restart all # Command để pull code từ repository trên server
