name: Deploy Node.js App

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Clear Cache
              run: sudo npm cache clean -f

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: Deploy to Server
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  USER: ${{ secrets.USER }}
                  HOST: ${{ secrets.HOST }}
                  DEST: /var/www/node-test/server
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
                  ssh $USER@$HOST "
                    cd $DEST && \
                    git pull origin master && \
                    npm install && \
                    pm2 reload ecosystem.config.js --env production
                  "
